# Site settings
title: Cedric Fung (vecio)
description: "Strive to formulate elegant code, simple design and friendly machine."
url: "https://vec.io"

# Build settings
permalink: /posts/:title
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [autolink, no_intra_emphasis, strikethrough, tables, lax_spacing, space_after_headers, superscript]

assets:
  cache: false
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor

author:
  full_name: Cedric Fung
  username: vecio
  avatar: https://secure.gravatar.com/avatar/8042491f13a3a828fcdd2a13290ef77d?r=g&s=256
  email: cedric@vec.io
  twitter: cedricfung
  github: vecio
  facebook: cedric.vec.io
